# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e0ad186ca2df0b217d17ef0066f4854cd356b5edcda3fcbf3ab420a3a30a78af11b9ab70c96552919a77c54b73c3acadad27c176cd0f5c8210644ba92197508

test:
  secret_key_base: 4f39f44e5e81dc41a3edc0bca9af09a5a557b199db02f6051a3c600eb3ec5279e01d608c2246cbd0f8bc5486eaf84c613c2a065780be44168578e36745494d59

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
